server:
  port: 8761
spring:
  application:
    name: Eureka-Server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  file:
    name: G:\HRMS_API\Eureka\app.log
  level:
    '[com.netflix.eureka]': debug
    '[com.netflix.discovery]': debug
    